server:
  port: 8097
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
    registry-fetch-interval-seconds: 15
  instance:
    prefer-ip-address: true
spring:
  application:
    name: eureka-client-zuul
zuul:
  # prefix: /common # 为zuul设置一个公共的前缀
  # 需要忽略的头部信息，不在传播到其他服务(zuul开启跨域时需要配置)
  # sensitive-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin
  routes:
    api-ribbon:
      # url: http://localhost:9001/
      path: /ribbon/**
      service-id: eureka-client-ribbon
    api-feign:
      path: /feign/**
      service-id: eureka-client-feign
    api-msgpush:
      path: /msgpush/**
      service-id: cloud-msg-push
