server:
  port: 8097
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: eureka-client-zuul
zuul:
  # prefix: /common #为zuul设置一个公共的前缀
  routes:
    api-ribbon:
      # url: http://localhost:9001/
      path: /ribbon/**
      service-id: eureka-client-ribbon
    api-feign:
      path: /feign/**
      service-id: eureka-client-feign
    api-msgpush:
      path: /msgpush/**
      service-id: cloud-msg-push
